### ISSUE TITLE
not working in Firefox 98.0 (64-bit)

### ISSUE THREAD

**Issue by Gatienzo** [ivocass/instagram-redesigned#2]
Hi. I don´t know what can be the problem but Instagram redesignedis not workingg in Firefox 98.0 (64-bit) in Windows 10.
I reinstalled but failed.
I also use facebook container plugin.
Thanks

**Comment by ivocass** [comment]
Hey there. No problems here (also on Firefox 98 and Windows 10). I uninstalled and reinstalled the latest version of the extension (v0.0.2.5) and had no issues.
Maybe you could test disabling the facebook container plugin.
How's the extension failing for you?
