### ISSUE TITLE
It is not working

### ISSUE THREAD

**Issue by Gatienzo** [ivocass/instagram-redesigned#4]
It is not working in 101.0 (64-bit).
I uninstalled and installed again with no luck.
I hope there is a fix, I like it.

**Comment by ivocass** [comment]
Hi, thanks for letting me know. I fixed everything that was broken by Instagram's update, except for Dark Mode, which is too costly too maintain.
I've already submitted version 0.0.3.0 to Firefox and Chrome. They should be available soon.
