### ISSUE TITLE
Dark theme fix

### ISSUE THREAD

**Issue by CrackHub** [ivocass/instagram-redesigned#5]
Instagram's website has a dark mode, but the only way to enable it is to append **?theme=dark** to every URL.

Can you add this in your extension?

**Comment by ivocass** [comment]
Dude, that's amazing! I had no idea, haha. I'll add it right away to v0.0.3.1.
It'll be in nav bar > Avatar dropdown> Dark mode.

**Comment by CrackHub** [comment]
Hi something going wrong.
If i use like this link, it is going refresh loop
https://www.instagram.com/?hl=en

Easy fix like this
https://www.instagram.com/?hl=en&theme=dark

**Comment by ivocass** [comment]
@CrackHub it's fixed now in version 0.0.3.2, which I've already submitted for Chrome and Firefox, and should be approved soon.
Thanks for everything!
