### ISSUE TITLE
Dark theme toogle button not showing

### ISSUE THREAD

**Issue by dbiagi** [ivocass/instagram-redesigned#7]
When opening the user menu it should show the dark theme toggle button, but is not there anymore.
![image](https://user-images.githubusercontent.com/6682510/204935448-7f18e328-4629-4384-a187-8e166737466b.png)

**Comment by ivocass** [comment]
Hey @dbiagi thanks for reporting the issue.
Right now Instagram is testing a new sidebar, which most of the users have.

![2022 12 02-13 52 57](https://user-images.githubusercontent.com/13630127/205344847-def4acc4-ff67-4005-b223-e86ec1d2ba4e.png)

Also, Google removed this add-on from the extensions store again, as Instagram made a copyright claim.
I'm still considering whether I should recreate the extension and publish it again.

**Comment by edizbaha** [comment]
@ivocass I really like your extension. It has a really good layout. I would appreciate it if you could do it again for the new navbar. Please don't discontinued this project. :)

**Comment by ivocass** [comment]
Hey @dbiagi, Instagram has now added this functionality to the site. So we don't need an extension to switch to the dark mode anymore.
![2022 12 26-12 13 18](https://user-images.githubusercontent.com/13630127/209562643-2593e15b-5be9-4610-8c1b-4c63a70d8bad.jpg)

This extension ("Redesign for Instagram") is now published under a new name, "Social redesign".
Here's the link: https://chrome.google.com/webstore/detail/social-redesign/fogcfagnihhjclemiamiaofgcbjgleop
