### ISSUE TITLE
Latest version not appearing on Firefox add-ons page

### ISSUE THREAD

**Issue by andy-kelly** [ivocass/instagram-redesigned#8]
The latest version of this add-on appears to be 0.0.3.5 but the latest version on the Firefox add-ons page is 0.0.3.3. Is it possible to push the latest version for Firefox?

**Comment by ivocass** [comment]
Done! I've just submitted v0.0.3.5 for review. Mozilla should publish it soon.

**Comment by andy-kelly** [comment]
Is it possible to get version 0.0.4.1 for Firefox?

**Comment by ivocass** [comment]
> Is it possible to get version 0.0.4.1 for Firefox?

Sure. I'll look into that as soon as I have some free time. Sorry for the delay.
